stages:          
  - build

build-job:       
  stage: build
  image: alpine:latest
  tags:
    - deploy
  script:
    - apk add --update openssh-client
    - ssh -T git@gitlab.com "mkdir /usr/testdir"

