version: "3.3"
networks:
  backend:
    driver: bridge
services:
  app:
    container_name: backend
    env_file: ./bushtree/.env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    networks:
      - backend
    depends_on:
      - postgress
    volumes:
      - ./scripts:/scripts
  postgress:
    container_name: postgres_db
    image: postgres
    env_file: ./bushtree/.env
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: umbrellamixmail@gmail.com
      PGADMIN_DEFAULT_PASSWORD: terrarik22
    ports:
      - "5433:5433"
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgress
  mongodb:
    image: mongo:latest
    container_name: mongo_bushtree
    environment:
      MONGO_INITDB_ROOT_USERNAME: Modestra
      MONGO_INITDB_ROOT_PASSWORD: Terrarik22
    ports:
      - "27017:27017"
    volumes:
      - ./mongoDb:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
volumes:
  dbdata6:
  postgres-data:
  pgadmin:
