version: "3.3"
networks:
  backend:
    driver: bridge
services:
  app:
    container_name: backend
    env_file: ./bushtree/.env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 6000:8000
    networks:
      - backend
    depends_on:
      - postgress
  postgress:
    container_name: bush_postgres_db
    image: postgres
    env_file: ./bushtree/.env
    ports:
      - "5532:5432"
    networks:
      - backend
    volumes:
      - postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: umbrellamixmail@gmail.com
      PGADMIN_DEFAULT_PASSWORD: terrarik22
    ports:
      - "5533:5433"
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgress
volumes:
  postgres-data:
  pgadmin:
