# Generated by Django 5.1.3 on 2024-12-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('frost_resistance_zone', models.IntegerField()),
                ('light', models.TextField(null=True)),
                ('watering', models.TextField(null=True)),
                ('color_main', models.TextField(null=True)),
                ('color_other', models.TextField(null=True)),
                ('height_from', models.IntegerField(null=True)),
                ('height_to', models.IntegerField(null=True)),
                ('decorative_terms_start', models.TextField(null=True)),
                ('decorative_terms_end', models.TextField(null=True)),
                ('flower_color', models.TextField(null=True)),
                ('leaf_color', models.TextField(null=True)),
                ('storage_before_planting', models.TextField(null=True)),
                ('landing_place', models.TextField(null=True)),
                ('soil_requirements', models.TextField(null=True)),
                ('boarding', models.TextField(null=True)),
                ('care', models.TextField(null=True)),
                ('reproduction', models.TextField(null=True)),
                ('use_in_landscape_design', models.TextField(null=True)),
                ('cleaning_for_the_winter', models.TextField(null=True)),
                ('shelter_for_the_winter', models.TextField(null=True)),
                ('pruning', models.TextField(null=True)),
                ('winter_hardiness', models.TextField(null=True)),
                ('keeping', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlowerBand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('flower_band_id', models.IntegerField(default=0)),
                ('mass', models.PositiveIntegerField()),
                ('flower_band', models.FileField(upload_to='flowerband/')),
            ],
        ),
        migrations.CreateModel(
            name='FlowerDataset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('frost_resistance_zone', models.IntegerField(default=0, null=True)),
                ('light', models.TextField(null=True)),
                ('watering', models.TextField(null=True)),
                ('color_main', models.TextField(null=True)),
                ('color_other', models.TextField(null=True)),
                ('height_from', models.IntegerField(null=True)),
                ('height_to', models.IntegerField(null=True)),
                ('decorative_terms_start', models.TextField(null=True)),
                ('decorative_terms_end', models.TextField(null=True)),
                ('cloud_number', models.TextField(null=True)),
                ('flower_beds', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('garden_id', models.IntegerField(default=0)),
                ('gardens', models.FileField(upload_to='garden/')),
            ],
        ),
    ]
