# Generated by Django 4.1 on 2024-10-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bushtree", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flowers",
            name="color_main",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="flowers",
            name="color_other",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="flowers",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="flowers",
            name="light",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="flowers",
            name="name",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="flowers",
            name="period_bloosom_end",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="flowers",
            name="period_bloosom_start",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="flowers",
            name="watering",
            field=models.TextField(null=True),
        ),
    ]
