# Generated by Django 5.1.3 on 2025-09-21 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bushtree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('flower_band', models.FileField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='MediaRegistration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('basedir', models.TextField()),
                ('filename', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='flowerband',
            name='flower_band_id',
        ),
        migrations.RemoveField(
            model_name='flowerband',
            name='mass',
        ),
        migrations.AlterField(
            model_name='flowerband',
            name='flower_band',
            field=models.FileField(upload_to='flowerbands/'),
        ),
        migrations.AlterField(
            model_name='garden',
            name='gardens',
            field=models.FileField(upload_to='gardens/'),
        ),
    ]
