# Generated by Django 5.1.3 on 2025-09-21 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bushtree', '0002_imagesmodel_mediaregistration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flowerband',
            old_name='flower_band',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='garden',
            old_name='gardens',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='imagesmodel',
            old_name='flower_band',
            new_name='file',
        ),
    ]
