# Generated by Django 5.1.3 on 2025-09-22 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bushtree', '0003_rename_flower_band_flowerband_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='garden',
            old_name='garden_id',
            new_name='flower_count',
        ),
    ]
