# Generated by Django 5.1.3 on 2024-11-28 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bushtree', '0004_flowerband_flowerdataset_garden_delete_gardens_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowerband',
            name='flower_band',
            field=models.FileField(upload_to='flowerband/'),
        ),
        migrations.AlterField(
            model_name='garden',
            name='gardens',
            field=models.FileField(upload_to='garden/'),
        ),
    ]
