# Generated by Django 5.1.3 on 2025-09-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bushtree', '0004_rename_garden_id_garden_flower_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='flower_id',
            field=models.IntegerField(default=0),
        ),
    ]
