# Generated by Django 5.1.3 on 2024-11-28 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bushtree', '0005_alter_flowerband_flower_band_alter_garden_gardens'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowerband',
            name='flower_band_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='garden',
            name='garden_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flowerdataset',
            name='expansion_id',
            field=models.IntegerField(null=True),
        ),
    ]
